version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ToDoDb
      MYSQL_ROOT_PASSWORD: "Password123!"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  mysql_data: